import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Player, FS_SDK_EVENTS_NAME } from 'furioos-sdk';
import { useEffect } from 'react';


export default function Home() {
  const options = {
    whiteLabel: true,
    hideToolbar: false,
    hideTitle: true,
    hidePlayButton: false,
    inactiveTimeout: 60000,
  };

  let player = null

  useEffect(() => {
    player = new Player("vqanXF2Z2tMv8xnt2" ,"container", options);
  }, [])
  
  if (player !== null ) {
  
    player.on(FS_SDK_EVENTS_NAME.LOAD, function() {
      console.log("SDK client FIRED: Player loaded");
    });
    
    // Bind application install progress
    player.on(FS_SDK_EVENTS_NAME.ON_APP_INSTALL_PROGRESS, function(data) {
      console.log("SDK client FIRED: App install progress", data);
    });
    
    // Bind application start
    player.on(FS_SDK_EVENTS_NAME.ON_APP_START, function() {
      console.log("SDK client FIRED: App start");
    });
    
    // Bind stream start
    player.on(FS_SDK_EVENTS_NAME.ON_STREAM_START, function() {
      console.log("SDK client FIRED: Stream start");
    });
    
    // Bind stream start
    player.on(FS_SDK_EVENTS_NAME.ON_SDK_START, function() {
      console.log("SDK client FIRED: SDK start");
    });
    
    // Bind SDK messages
    player.on(FS_SDK_EVENTS_NAME.ON_SDK_MESSAGE, function(data) {
      console.log("SDK Message Received:", data);
    });
    
    // Bind an event that lets you know if you can resume session
    player.on(FS_SDK_EVENTS_NAME.ON_RESUME_SESSION, function({ canResumeSession }) {
      if(canResumeSession) {
        player.resumeSession();
      }
    });
    
    // Bind session stoppeds
    player.on(FS_SDK_EVENTS_NAME.ON_SESSION_STOPPED, function() {
      console.log("SDK client FIRED: Session Stopped");
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id='container' className='w-[80vw] h-[80vh]'/>
      </main>
    </div>
  )
}
